version: '3.8'

services:
  web:
    build: .
    image: web:latest
    ports:
      - "8443:8443"
    environment:
      APACHE_SSL_REQUIRE_CUSTOM_CERT: ${APACHE_SSL_REQUIRE_CUSTOM_CERT:-false}
      APACHE_SSL_CERT_FILE: ${APACHE_SSL_CERT_FILE:-/certs/server.crt}
      APACHE_SSL_KEY_FILE: ${APACHE_SSL_KEY_FILE:-/certs/server.key}
      APACHE_SSL_CHAIN_FILE: ${APACHE_SSL_CHAIN_FILE:-}
      APACHE_SSL_SELF_SIGNED_SUBJECT: ${APACHE_SSL_SELF_SIGNED_SUBJECT:-/CN=localhost}
      APACHE_SSL_SELF_SIGNED_DAYS: ${APACHE_SSL_SELF_SIGNED_DAYS:-365}
      DATABASE_HOST: ${DATABASE_HOST:-192.168.8.34}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-chamaweb}
      DATABASE_USER: ${DATABASE_USER:?DATABASE_USER not set}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD not set}
      MYSQL_SSL_CA: ${MYSQL_SSL_CA:-}
    volumes:
      - ./certs:/certs:ro
    depends_on:
      - db_check
      - gateway

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    image: gateway:latest
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-192.168.8.34}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-chamaweb}
      DATABASE_USER: ${DATABASE_USER:?DATABASE_USER not set}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD not set}
      MYSQL_SSL_CA: ${MYSQL_SSL_CA:-}
    depends_on:
      - db_check
      - tickets
      - stats

  tickets:
    build:
      context: .
      dockerfile: services/tickets/Dockerfile
    image: tickets:latest
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-192.168.8.34}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-chamaweb}
      DATABASE_USER: ${DATABASE_USER:?DATABASE_USER not set}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD not set}
      MYSQL_SSL_CA: ${MYSQL_SSL_CA:-}
    depends_on:
      - db_check

  stats:
    build:
      context: .
      dockerfile: services/stats/Dockerfile
    image: stats:latest
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-192.168.8.34}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-chamaweb}
      DATABASE_USER: ${DATABASE_USER:?DATABASE_USER not set}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD not set}
      MYSQL_SSL_CA: ${MYSQL_SSL_CA:-}
    depends_on:
      - db_check

  db_check:
    image: busybox
    command: ["sh", "-c", "until nc -z ${DATABASE_HOST:-192.168.8.34} ${DATABASE_PORT:-3306}; do echo waiting for db; sleep 2; done; echo db reachable"]
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-192.168.8.34}
      - DATABASE_PORT=${DATABASE_PORT:-3306}
    restart: "no"
