version: "3.8"

services:
  kali:
    image: kalilinux/kali-rolling
    hostname: kali
    networks:
      internet:
        ipv4_address: 10.10.0.2
    volumes:
      - ./scripts:/scripts:ro
      - ./scripts/bootstrap_kali.sh:/bootstrap_kali.sh:ro
    entrypoint: ["/bin/bash", "/bootstrap_kali.sh"]
    command: ["tail", "-f", "/dev/null"]

  fw:
    build: ./fw
    networks:
      internet:
        ipv4_address: 10.10.0.1
      dmz:
        ipv4_address: 10.20.0.1
      internal:
        ipv4_address: 10.30.0.1
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "8.8.8.8"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx-waf:
    build: ./nginx
    depends_on:
      - fw
      - api-gateway
    networks:
      dmz:
        ipv4_address: 10.20.0.10
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./logs/nginx:/var/log/nginx
      - ./scripts:/scripts:ro
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  api-gateway:
    build: ./api
    networks:
      internal:
        ipv4_address: 10.30.0.10
    secrets:
      - db_user
      - db_password
    depends_on:
      - mysql
      - keycloak
    environment:
      DB_HOST: mysql
      DB_NAME: appdb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  mysql:
    image: mysql:8
    networks:
      internal:
        ipv4_address: 10.30.0.20
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    secrets:
      - db_root_password
      - db_user
      - db_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]
    networks:
      internal:
        ipv4_address: 10.30.0.30
    environment:
      KEYCLOAK_ADMIN_FILE: /run/secrets/kc_admin_user
      KEYCLOAK_ADMIN_PASSWORD_FILE: /run/secrets/kc_admin_password
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/chamaweb-realm.json
    volumes:
      - ./keycloak/chamaweb-realm.json:/opt/keycloak/data/import/chamaweb-realm.json:ro
    secrets:
      - kc_admin_user
      - kc_admin_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 5

  wazuh:
    image: busybox
    command: ["sh", "-c", "echo 'Wazuh placeholder' && sleep infinity"]
    profiles: ["wazuh"]
    networks:
      internal:
        ipv4_address: 10.30.0.40

secrets:
  db_user:
    file: ./secrets/db_user.example
  db_password:
    file: ./secrets/db_password.example
  db_root_password:
    file: ./secrets/db_root_password.example
  kc_admin_user:
    file: ./secrets/kc_admin_user.example
  kc_admin_password:
    file: ./secrets/kc_admin_password.example

networks:
  internet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/24
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 10.30.0.0/24

volumes:
  mysql_data:
