version: '3.8'

services:
  web:
    build: .
    image: web:latest
    ports:
      - "8443:443"
    depends_on:
      - gateway

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    image: gateway:latest
    depends_on:
      - tickets
      - stats

  tickets:
    build:
      context: .
      dockerfile: services/tickets/Dockerfile
    image: tickets:latest
    depends_on:
      - db

  stats:
    build:
      context: .
      dockerfile: services/stats/Dockerfile
    image: stats:latest
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chamaweb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
      - ./script_sql.sql:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root


volumes:
  db_data:
