version: '3.8'

services:
  web:
    build: .
    image: web:latest
    ports:
      - "8443:8443"
    environment:
      APACHE_SSL_REQUIRE_CUSTOM_CERT: ${APACHE_SSL_REQUIRE_CUSTOM_CERT:-false}
      APACHE_SSL_CERT_FILE: ${APACHE_SSL_CERT_FILE:-/certs/server.crt}
      APACHE_SSL_KEY_FILE: ${APACHE_SSL_KEY_FILE:-/certs/server.key}
      APACHE_SSL_CHAIN_FILE: ${APACHE_SSL_CHAIN_FILE:-}
      APACHE_SSL_SELF_SIGNED_SUBJECT: ${APACHE_SSL_SELF_SIGNED_SUBJECT:-/CN=localhost}
      APACHE_SSL_SELF_SIGNED_DAYS: ${APACHE_SSL_SELF_SIGNED_DAYS:-365}
      DATABASE_HOST: ${DATABASE_HOST:-192.168.8.34}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-chamaweb}
      DATABASE_USER: ${DATABASE_USER:-app_user}
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-08^8nG0E9U@a}"
      MYSQL_SSL_CA: ${MYSQL_SSL_CA:-}
    volumes:
      - ./certs:/certs:ro
    tmpfs:
      - /run/apache2:rw,noexec,nosuid,nodev,size=4M,mode=0750
      - /var/www/html/tmp:rw,noexec,nosuid,nodev,size=32M,uid=33,gid=33,mode=0770
      - /var/www/html/uploads:rw,noexec,nosuid,nodev,size=128M,uid=33,gid=33,mode=0770
      - /var/lib/php/sessions:rw,noexec,nosuid,nodev,size=32M,uid=33,gid=33,mode=1733
      - /tmp:rw,noexec,nosuid,nodev,size=16M,mode=1777
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        - CMD-SHELL
        - 'php -r ''exit(@fsockopen("127.0.0.1", 8443) ? 0 : 1);'''
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - db_check
      - gateway

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    image: gateway:latest
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-192.168.8.34}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-chamaweb}
      DATABASE_USER: ${DATABASE_USER:-app_user}
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-08^8nG0E9U@a}"
      MYSQL_SSL_CA: ${MYSQL_SSL_CA:-}
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=16M,mode=1777
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        - CMD-SHELL
        - 'php -r ''exit(@fsockopen("127.0.0.1", 80) ? 0 : 1);'''
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - db_check
      - tickets
      - stats

  tickets:
    build:
      context: .
      dockerfile: services/tickets/Dockerfile
    image: tickets:latest
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-192.168.8.34}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-chamaweb}
      DATABASE_USER: ${DATABASE_USER:-app_user}
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-08^8nG0E9U@a}"
      MYSQL_SSL_CA: ${MYSQL_SSL_CA:-}
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=16M,mode=1777
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        - CMD-SHELL
        - 'php -r ''exit(@fsockopen(getenv("DATABASE_HOST") ?: "192.168.8.34", getenv("DATABASE_PORT") ?: 3306) ? 0 : 1);'''
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - db_check

  stats:
    build:
      context: .
      dockerfile: services/stats/Dockerfile
    image: stats:latest
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-192.168.8.34}
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_NAME: ${DATABASE_NAME:-chamaweb}
      DATABASE_USER: ${DATABASE_USER:-app_user}
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-08^8nG0E9U@a}"
      MYSQL_SSL_CA: ${MYSQL_SSL_CA:-}
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=16M,mode=1777
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        - CMD-SHELL
        - 'php -r ''exit(@fsockopen(getenv("DATABASE_HOST") ?: "192.168.8.34", getenv("DATABASE_PORT") ?: 3306) ? 0 : 1);'''
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      - db_check

  db_check:
    image: busybox
    command: ["sh", "-c", "until nc -z ${DATABASE_HOST:-192.168.8.34} ${DATABASE_PORT:-3306}; do echo waiting for db; sleep 2; done; echo db reachable"]
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-192.168.8.34}
      - DATABASE_PORT=${DATABASE_PORT:-3306}
    restart: "no"
