apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway:latest
        # Usamos imagens locais carregadas no Minikube, então evitamos que o
        # Kubernetes tente fazer pull de um registry externo.
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
